config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'dashboard#index'

  resources :dashboard, only: [:index]

  resources :sections, except: [:new], controller: 'sections' do 
    resources :activities, controller: 'sections/activities'
  end

end

app/models/activity.rb
class Activity < ApplicationRecord
  extend FriendlyId
  friendly_id :nama_kegiatan, use: :slugged

  WillPaginate.per_page = 5

  belongs_to :section, counter_cache: true

  counter_cache_with_conditions :section, :activities_achieved, status: 1

  validates :nama_kegiatan, presence: {message: 'Harus diisi, tidak boleh kosong!'}
  validates :status, numericality: {message: 'Harus dipilih!'}
  validates :target_pelaksanaan, presence: {message: 'Harus diisi, tidak boleh kosong!'}
  validates :realisasi_pelaksanaan, presence: {message: 'Harus diisi, tidak boleh kosong!'}, if: :status_equal_one 

  def status_equal_one
    status == 1
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/section.rb
class Section < ApplicationRecord
  extend FriendlyId
  friendly_id :nama_bidang, use: :slugged

  has_many :activities, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :set_header

  def index
    @section = Section.all
  end

  private

    def set_header
      @sections = Section.all
    end
end

app/controllers/sections/activities_controller.rb
class Sections::ActivitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_header
  before_action :set_section, except: [:show]
  before_action :set_activity, only: [:edit, :update, :destroy]

  def index
    @activities = @section.activities.where('nama_kegiatan like ?', "%#{params[:search]}%").paginate(per_page: 5, page: params[:page])
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)

    @activity.section = @section
    if @activity.save
      flash[:notice] = 'Kegiatan berhasil ditambahkan!'
      redirect_to section_activities_path(@section)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @activity.update(activity_params)
      flash[:notice] = 'Kegiatan berhasil diupdate!'
      redirect_to section_activities_path(@section)
    else
      render 'edit'
    end
  end

  def destroy
    @activity.destroy
    flash[:notice] = 'Kegiatan berhasil dihapus!'
    redirect_to section_activities_path(@section)
  end

  private 
    def set_header
      @sections = Section.all
    end

    def set_section
      @section = Section.friendly.find(params[:section_id])
    end

    def set_activity
      @activity = Activity.friendly.find(params[:id])
    end
    
    def activity_params
      params.require(:activity).permit(:nama_kegiatan, :target_pelaksanaan, :realisasi_pelaksanaan, :status, :section_id)
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_header
  before_action :set_section, only: [:edit, :update, :destroy]

  def index
    @sections = Section.all
    @section = Section.new
  end

  def create
    @section = Section.new(section_params)

    if @section.save
      flash[:notice] = 'Bidang berhasil ditambahkan!'
      redirect_to sections_path
    else
      render 'index'
    end
  end

  def edit
  end

  def update
    if @section.update(section_params)
      flash[:notice] = 'Bidang berhasil diperbarui!'
      redirect_to sections_path
    else
      render 'edit'
    end
  end

  def destroy
    if @section.destroy
      flash[:notice] = 'Bidang berhasil dihapus!'
      redirect_to sections_path
    end
  end

  private

    def set_header
      @section = Section.all
    end

    def set_section
      @section = Section.friendly.find(params[:id])
    end

    def section_params
      params.require(:section).permit(:nama_bidang)
    end
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/section_helper.rb
module SectionHelper
end

app/views/dashboard/index.html.erb
<% if flash[:notice].present? %>
  <div class="col-12">
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <strong><%= flash[:notice] %></strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
<% end %>
<% if @sections.present? %>
  <div class="col-12">
    <h5 class="font-weight-bold text-danger" style="margin-bottom: -10px;">Info Kegiatan</h5>
  </div>
  <% @section.each do |b| %>
    <div class="col-4" style="margin-top: 20px;">
      <div class="card border-primary" >
        <div class="card-header bg-primary text-white font-weight-bold" ><%= b.nama_bidang %></div>
        <div class="card-body text-secondary font-weight-bold">
          <i class="fa fa-calculator"></i> Jumlah : <h2 class="text-danger font-weight-bold">&nbsp;&nbsp;&nbsp;&nbsp;<%= b.activities_count %> Kegiatan</h2>
          <i class="fa fa-check-square"></i> Sudah dilaksanakan : <h2 class="text-danger font-weight-bold">&nbsp;&nbsp;&nbsp;&nbsp;<%= b.activities_achieved %> Kegiatan</h2>
        </div>
      </div>
    </div>
  <% end %>

  <div class="col-12" style="margin-top: 25px;">
    <h5 class="font-weight-bold text-danger">Persentase Pelaksanaan Kegiatan</h5>
  </div>
  <% @section.each do |b| %>
    <div class="col-3">
      <label>
        <%= b.nama_bidang %>
      </label>
    </div>
    <div class="col-12">
      <div class="progress" >
        <% c = b.activities_achieved.to_f / b.activities_count.to_f * 100 %>
        <div class="progress-bar" role="progressbar" style="width: <%= c.round(2) %>%;" aria-valuenow="<%= c.round(2) %>" aria-valuemin="0" aria-valuemax="100">
          <%= c.round(2) %> %
        </div>
      </div>
    </div><br />
  <% end %>
<% else %>
  <h5 class="font-weight-bold text-danger">Bidang belum ditambahkan!</h5>
<% end %>

app/views/layouts/_footer.html.erb
  </div>
</section>

app/views/layouts/_header.html.erb
<% if user_signed_in? %>
  <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
      <a class="navbar-brand" href="#">PROKER 2018</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <% if controller.controller_name == 'dashboard' %>active<% end %> text-white">
            <%= link_to 'Dashboard', dashboard_index_path, class: 'nav-link text-white' %>
          </li>
          <li class="nav-item <% if controller.controller_name == 'sections' %>active<% end %> text-white">
            <%= link_to 'Bidang', sections_path, class: 'nav-link text-white' %>
          </li>
          <% if @sections.present? %>
            <li class="nav-item dropdown <% if controller.controller_name == 'activities' %>active<% end %> text-white">
              <%= link_to 'Kegiatan', '#', class: 'text-white nav-link dropdown-toggle', id: 'navbarDropdown', data: {toggle: 'dropdown'}, aria: {haspopup: true, expanded: false} %>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <% @sections.each do |s| %>
                  <%= link_to s.nama_bidang, section_activities_path(s), class: 'dropdown-item text-danger' %>
                <% end %>
              </div>
            </li>
          <% end %>
        </ul>
        <ul class="navbar-nav">
          <li class="nav-item">
            <span class="nav-link text-white">Hi, <%= current_user.username.titleize %></span>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link text-white' %>
          </li>
        </ul>
      </div>
    </nav>
  </header>
<% end %> 
  <section class="container">
    <div class="row">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proker2018</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/section/show.html.erb
<div class="col-12 text-center">
  <h3 class="font-weight-bold"><%= @bidang.nama_bidang %></h3>
</div>
<div class="col-12" style="margin-top: 20px;">
  <%= link_to 'Tambah kegiatan', new_section_activity_path(@bidang), class: 'btn btn-primary', style: 'border-radius: 0;' %>
</div>
<div class="col-12" style="margin-top: 20px;">
  <% no = 0 %>
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>No.</th>
        <th>Nama Kegiatan</th>
        <th>Target Awal Pelaksanaan</th>
        <th>Realisasi</th>
        <th>Status</th>
        <th>Aksi</th>
      </tr>
    </thead>
    <tbody>
      <% @bidang.activities.each do |a| %>
        <tr>
          <td><%= no += 1 %></td>
          <td><%= a.nama_kegiatan %></td>
          <td><%= a.realisasi_pelaksanaan %></td>
          <td><%= a.target_pelaksanaan %></td>
          <td>
            <% if a.status == 0 %>
              <span class="text-warning"><i class="fa fa-exclamation-triangle"></i></span>
            <% elsif a.status == 1 %>
              <span class="text-success"><i class="fa fa-check-square"></i></span>
            <% end %>
          </td>
          <td>
              <i class="fa fa-pencil"></i> | <i class="fa fa-trash"></i>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<div class="col-12">
  <span class="text-danger">*</span> <i class="font-weight-bold">Keterangan</i> : <br />
  <span class="text-success"><i class="fa fa-check-square"></i></span> = Sudah dilaksanakan <br />
  <span class="text-warning"><i class="fa fa-exclamation-triangle"></i></span> = Belum dilaksanakan
</div>

app/views/sections/activities/_form.html.erb
<div class="col-12">
  <%= form_for [@section, @activity] do |f| %>

    <%= f.label :nama_kegiatan %>
    <% if @activity.errors[:nama_kegiatan].any? %>
      <span class="text-danger"><%= @activity.errors[:nama_kegiatan].first %></span>
    <% end %>
    <%= f.text_field :nama_kegiatan, class: 'form-control', placeholder: 'Nama kegiatan' %>
    <br />
    
    <%= f.label :status_kegiatan %>
    <br />
    <% if @activity.errors[:status].any? %>
      <span class="text-danger"><%= @activity.errors[:status].first %></span>
    <% end %>
    <%= f.select :status, [['Pilihan...', ''], ['Belum dilaksanakan', 0], ['Sudah dilaksanakan', 1]], {}, {class: 'form-control', id: 'status', onclick: 'disableField(this.id, this.value)'} %>
    <br />

    <%= f.label :rencana_awal_pelaksanaan %>
    <br />
    <% if @activity.errors[:target_pelaksanaan].any? %>
      <span class="text-danger"><%= @activity.errors[:target_pelaksanaan].first %></span>
    <% end %>
    <%= f.text_field :target_pelaksanaan, class: 'form-control monthpicker', placeholder: 'mm/yyyy' %>
    <br />
    
    <%= f.label :realisasi_pelaksanaan %>
    <% if @activity.errors[:realisasi_pelaksanaan].any? %>
      <span class="text-danger"><%= @activity.errors[:realisasi_pelaksanaan].first %></span>
    <% end %>
    <%= f.text_field :realisasi_pelaksanaan, class: 'form-control monthpicker', id: 'realisasi', placeholder: 'mm/yyyy'  %>
    <%= f.hidden_field :realisasi_pelaksanaan, id: 'realisasi_pelaksanaan'  %>
    <br />

    <%= link_to 'Batal', section_activities_path(@section), class: 'btn btn-secondary' %>
    <%= f.submit 'Simpan', class: 'btn btn-primary' %>
  <% end %>
</div>

<script>
  document.getElementById("realisasi").disabled = true;
  function disableField(id, value)
  {
    s = document.getElementById(id).value;

    if(s == 0)
    {
      document.getElementById("realisasi").disabled = true;
      document.getElementById("realisasi_pelaksanaan").disabled = false;
      document.getElementById("realisasi_pelaksanaan").value = null;
    }
    else if(s == 1)
    {
      document.getElementById("realisasi").disabled = false;
      document.getElementById("realisasi_pelaksanaan").disabled = true;
    }
  }

  $(function () {
    $('input.monthpicker').monthpicker({changeYear:true, minDate: "-3 M", maxDate: "+2 Y" });
  });
</script>

app/views/sections/activities/edit.html.erb
<div class="col-12 text-center">
  <h3 class="text-secondary">Edit Kegiatan di <%= @section.nama_bidang %></h3>
</div>

<%= render 'form' %>

app/views/sections/activities/index.html.erb
<% if flash[:notice].present? %>
  <div class="col-12">
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <strong><%= flash[:notice] %></strong>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  </div>
<% end %>
<div class="col-12 text-secondary text-center">
  <h3 class="font-weight-bold"><%= @section.nama_bidang %></h3>
</div>

<div class="col-9" style="margin-top: 20px;">
  <%= link_to 'Tambah kegiatan', new_section_activity_path(@section), class: 'btn btn-primary', data: {turbolinks: false} %>
</div>

<div class="col-3" style="margin-top: 20px;">
  <%= form_tag section_activities_path(@section, @activity), method: :get do %>
    <div class="input-group">
      <%= text_field_tag :search, nil, class: 'form-control', placeholder: 'Cari kegiatan' %>
      <div class="input-group-append">
        <%= submit_tag 'Cari', class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

<div class="col-12 text-secondary" style="margin-top: 20px;">
  <table class="table table-bordered">
    <thead>
      <tr>
        <th>No.</th>
        <th>Nama Kegiatan</th>
        <th>Target Awal Pelaksanaan</th>
        <th>Realisasi</th>
        <th>Status</th>
        <th>Aksi</th>
      </tr>
    </thead>
    <tbody>
      <% if @activities.present? %>
        <% no = ((params[:page] || 1).to_i - 1) * 5 %>
        <% @activities.each do |a| %>
          <tr>
            <td><%= no += 1 %></td>
            <td><%= a.nama_kegiatan %></td>
            <td><%= a.target_pelaksanaan %></td>
            <td><%= a.realisasi_pelaksanaan %></td>
            <td>
              <% if a.status == 0 %>
                <% if a.target_pelaksanaan[0...2] <= Date.today.strftime("%m") %>
                  <span class="text-warning"><i class="fa fa-exclamation-triangle"></i></span>
                <% elsif a.target_pelaksanaan[0...2] > Date.today.strftime("%m") %>
                  <span class="text-info"><i class="fa fa-paper-plane"></i></span>
                <% end %>
              <% elsif a.status == 1 %>
                <span class="text-success"><i class="fa fa-check-square"></i></span>
              <% end %>
            </td>
            <td>
              <%= link_to edit_section_activity_path(@section, a.slug), title: 'Ubah', data: {turbolinks: false} do %><i class="fa fa-pencil text-secondary"></i><% end %> 
              <%= link_to section_activity_path(@section, a.slug), method: :delete, data: { confirm: 'Apakah anda yakin akan menghapus kegiatan ini?' }, title: 'Hapus' do %><i class="fa fa-trash text-secondary"></i><% end %> 
            </td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td style="border: none;"><span class="text-danger">Kegiatan belum ditambahkan!</span></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @activities, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>
<div class="col-12 text-secondary" style="font-size: 0.9rem;">
  <span class="text-danger"><i class="fa fa-tags"></i></span> <i class="font-weight-bold">Keterangan</i> : <br />
  <div class="ket-menu" style="margin-left: 19px;">
    <span class="text-success"><i class="fa fa-check-square"></i></span> = Sudah dilaksanakan <br />
    <span class="text-warning"><i class="fa fa-exclamation-triangle"></i></span> = Belum dilaksanakan <br />
    <span class="text-info"><i class="fa fa-paper-plane"></i></span> = On Progress
  </div>
</div>

app/views/sections/activities/new.html.erb
<div class="col-12 text-center">
  <h3 class="text-secondary">Tambah Kegiatan di <%= @section.nama_bidang %></h3>
</div>

<%= render 'form' %>

app/views/sections/edit.html.erb
<div class="col-12">
  <% if flash[:notice].present? %>
    <div class="col-12">
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong><%= flash[:notice] %></strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  <% end %>
  
  <%= form_for @section, html: {class: 'form-inline'} do |f| %>
    <div class="form-group mx-sm-3 mb-2">
      <%= f.text_field :nama_bidang, class: 'form-control', placeholder: 'Nama bidang' %>
    </div>
    <%= f.submit 'Update', class: 'btn btn-primary mb-2' %>
  <% end %>

  <div class="col-12">
    <hr>
  </div>

  <div class="col-12">
    <%= link_to 'Kembali', sections_path, class: 'btn btn-secondary' %>
  </div>

</div>

app/views/sections/index.html.erb
<div class="col-12">
  <% if flash[:notice].present? %>
    <div class="col-12">
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong><%= flash[:notice] %></strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  <% end %>
  
  <%= form_for @section, html: {class: 'form-inline'} do |f| %>
    <div class="form-group mx-sm-3 mb-2">
      <%= f.text_field :nama_bidang, class: 'form-control', placeholder: 'Nama bidang' %>
    </div>
    <%= f.submit 'Tambah', class: 'btn btn-primary mb-2' %>
  <% end %>

  <div class="col-12">
    <hr>
  </div>

  <div class="col-12">
    <% if @sections.present? %>
      <% @sections.each do |s| %>
          <div class="alert alert-dark">
            <h6 class="text-secondary font-weight-bold">Bidang <%= s.nama_bidang %></h6>
          </div>
      <% end %>
    <% else %>
      <h5 class="font-weight-bold text-danger">Bidang belum ditambahkan!</h5>
    <% end %>
  </div>
</div>